### ISSUE TITLE
noncomputable defs

### ISSUE THREAD

**Issue by fpvandoorn** [gebner/hott3#10]
I have a question about the `noncomputable` keyword. I thought that would disable bytecode generation of definitions. However, I still get an error when a noncomputable definition depends on a theorem:
```lean
noncomputable theory
theorem foo (m : ℕ) : ℕ := m + 1
def bar (m : ℕ) : ℕ := foo (m + 1)
```
I get the error
```
3:5: failed to generate bytecode for 'bar'
code generation failed, VM does not have code for 'foo'
```
Is there a way to have a `def` (which doesn't live in `Sort 0`) depending on a `theorem`? I want certain things to be `def`s to make them reducible and certain things `theorems` to make them irreducible (and not generate useless bytecode).

**Comment by gebner** [comment]
Indeed, `noncomputable` definitions do not get compiled into bytecode.  However, `noncomputable theory` does not imply that all definitions are `noncomputable`---it means that Lean decides which ones are `noncomputable`, and which ones are not.

So in the example, neither `foo` nor `bar` are noncomputable.

I'm not sure I can do anything about this issue in the Lean code base itself given the current political situation.  However, I can think of three workarounds:

1) Force bar to be noncomputable by including a useless beta-redex:
```lean
noncomputable def suppress_bytecode : unit :=
have _, from quotient.eq_of_rel (=) (idpath ()), ()

@[hott] theorem foo (m : ℕ) : ℕ := m + 1
@[hott] def bar (m : ℕ) : ℕ :=
have _, from suppress_bytecode,
foo (m + 1)
```

2) Use `@[irreducible] def` instead of theorem:
```lean
@[hott,irreducible] def foo (m : ℕ) : ℕ := m + 1
@[hott] def bar (m : ℕ) : ℕ :=
foo (m + 1)
```

3) Use the `type_context.unfold_lemmas` option:
```lean
@[hott,irreducible] theorem foo (m : ℕ) : ℕ := m + 1
@[hott] theorem bar (m : ℕ) : ℕ :=
foo (m + 1)

set_option type_context.unfold_lemmas true
example: bar 2 = foo 3 := idp
example: foo 2 = 3 := idp -- fails, since foo is still irreducible
```

(Nota bene: workaround 3 effectively prevents the lazy delta-reduction optimization, since we don't store the definitional height of theorems.)

**Comment by fpvandoorn** [comment]
Ok, thanks. I will turn some theorems into defs as a workaround.
