### ISSUE TITLE
Slightly unexpected definitional equalities

### ISSUE THREAD

**Issue by gebner** [gebner/hott3#6]
Due to the construction of the HITs, we get a few definitional equalities "for free":
```lean
example {n : ℕ₋₂} {A : Type u} {P : trunc n A → Type v} (Pt Pt') :
    @trunc.rec _ _ P Pt = @trunc.rec _ _ P Pt' :=
idp

example {A : Type u} {R : A → A → Type v} {P : quotient R → Type w}
        (Pc : Π(a : A), P (class_of R a)) (Pp Pp') :
    quotient.rec Pc Pp = quotient.rec Pc Pp' :=
idp
```

Essentially, we ignore the proofs that the elimination respects the truncation or the equivalence relation when checking definitional equality.  @fpvandoorn Is this a problem?  I can fix it if it is.

**Comment by fpvandoorn** [comment]
Yes, that's a problem. The second one is definitely inconsistent. For the first one I'm not sure (it is possible to prove that they are equal), but to be on the save side, it's better to not have them definitionally equal.

**Comment by gebner** [comment]
Good to know.  I didn't expect them to matter since they are lost in the definitional reductions.

**Comment by fpvandoorn** [comment]
Thanks!

> I didn't expect them to matter since they are lost in the definitional reductions.

Only when you apply the recursor to a point constructor, if you "apply" it to the path constructor `eq_of_rel`, you get `Pp` back (propositionally), see `rec_eq_of_rel`. This is similar that if you apply `nat.rec P0 PS` to `0` you only get back `P0`. You need to apply it to `succ` to get `PS` back.

**Comment by fpvandoorn** [comment]
I'm now looking more closely to `init.hit` (so far I've been porting the files `hit.quotient` imports, so that I could look at hits when porting that file), and the technique you used to implement HITs is the "Dan Licata trick", since he did it first in Agda. Here is the same trick used in Coq:
https://github.com/HoTT/HoTT/blob/master/theories/HIT/Coeq.v#L11-L32

They also use the same (or a very similar) trick to let the `match` depend on `Pc`/`Pt` so that you don't get the wrong definitional equalities.
