### ISSUE TITLE
recursors eliminating to `Type _`

### ISSUE THREAD

**Issue by fpvandoorn** [gebner/hott3#9]
This is the same issue as in #5: recursors currently can only be defined if they eliminate to `Prop` or `Sort _`. In the HoTT library, I would like to avoid `Prop` as much as possible, and defining recursors so that they eliminate to `Sort _` would require changing most of the library so that it accepts propositions as input.

For example: if we want that `trunc.rec` and `quotient.rec` (in `init.hit`) both eliminate to `Sort _`, we need to redefine `is_trunc n A`, `eq`, `pathover` to all accept `Prop`s (and when I tried that, I got universe issues, probably because we now have `max u 1` floating around in many places).

@gebner If you're willing to go through the code of the `[recursor]` attribute and the `induction` tactic, and support recursors to `Type _` (i.e. `Sort (_+1)`), then that would be great. If not, then that's also fine, and I'll try to write a `hinduction` tactic which does exactly that.

**Comment by gebner** [comment]
I agree, we should be using `Type` everywhere.  Mixing Type and Sort leads to the level inference problem you've seen.  Maybe it would work if we used Sort instead of Type everywhere, but that's not very pretty.

I am not sure I will be able to modify recursor_info and the induction tactic to support recursors eliminating into `Sort (u+1)`.  It's more than just a cosmetic change, and I'm not sure Leo would accept it.  I guess `hinduction` is the way to go.

**Comment by fpvandoorn** [comment]
The `hinduction` tactic now exists and works.
